CIFAR_PATH = '/home/raphael/dataspace/datasets/cifar-10-batches-py'
DIFFJPEG_PATH = '/home/raphael/workspace/libs/DiffJPEG'
OUTPUT_FOLDER_PATH = '/home/raphael/dataspace/outputs/easy_problem_attack'
AUG_PATH = '/home/raphael/dataspace/datasets/cifar-10-batches-py/cifar10_ddpm.npz'
MNIST_PATH = '/home/raphael/dataspace/datasets/mnist'
IMAGENET_PATH = '/home/raphael/dataspace/datasets/imagenette2'